apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dndapp-ingress
  namespace: dndapp
  labels:
    app.kubernetes.io/part-of: dndapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dndapp.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dndapp-backend
                port:
                  number: 8080
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: dndapp-backend
                port:
                  number: 8080
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: dndapp-backend
                port:
                  number: 8080
          # Когда появится фронтенд:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: dndapp-frontend
          #       port:
          #         number: 80
