apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dndapp

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patches/backend-replicas.yaml
  - path: patches/postgres-storage.yaml
  - path: patches/app-config.yaml

images:
  - name: dndapp-backend
    newName: your-registry.example.com/dndapp-backend
    newTag: latest
