apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndapp-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1Gi
