apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dndapp
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: dndapp
type: Opaque
stringData:
  POSTGRES_DB: dndapp
  POSTGRES_USER: dnd
  POSTGRES_PASSWORD: dnd
