package com.dnd.app.domain.enums;

public enum WebSocketEventType {
    ITEM_GRANTED,
    ITEM_REMOVED,
    BUFF_APPLIED,
    BUFF_REMOVED,
    XP_GRANTED,
    HP_CHANGED,
    CHARACTER_UPDATED,
    NPC_REVEALED,
    NPC_HIDDEN,
    MONSTER_REVEALED,
    MONSTER_HIDDEN,
    QUEST_UPDATED,
    CAMPAIGN_STATUS_CHANGED,
    MEMBER_KICKED,
    WALLET_CHANGED
}
