apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dndapp
  namespace: argocd
spec:
  description: D&D Character Management System
  sourceRepos:
    - "*"
  destinations:
    - namespace: dndapp
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
