apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dndapp
  labels:
    app.kubernetes.io/name: dndapp-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dndapp
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: dnd
  SPRING_DATASOURCE_PASSWORD: dnd
  APP_JWT_SECRET: CHANGE_ME_IN_PRODUCTION_USE_256_BIT_KEY_THAT_IS_LONG_ENOUGH
