apiVersion: v1
kind: Service
metadata:
  name: dndapp-backend
  namespace: dndapp
  labels:
    app.kubernetes.io/name: dndapp-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dndapp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dndapp-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
