apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dndapp

resources:
  - namespace.yaml
  # postgres
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  # backend
  - app/configmap.yaml
  - app/secret.yaml
  - app/deployment.yaml
  - app/service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
