apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dndapp

resources:
  - ../../base

patches:
  - path: patches/backend-replicas.yaml
    target:
      kind: Deployment
      name: dndapp-backend
  - path: patches/postgres-storage.yaml
    target:
      kind: PersistentVolumeClaim
      name: postgres-data

images:
  - name: dndapp-backend
    newName: dndapp-backend
    newTag: dev
